### ISSUE TITLE
🚧Change release todo issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#12]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the _**Preview**_ and _**Production**_ release todo issue templates have a section where you can list out all of the issues being released.  This is not required anymore because milestones are used to contain items for a release.  This is duplicate information and extra work to perform for every release and it is not required anymore.

Remove/change the areas in the template displayed in the diagram below.

![image](https://user-images.githubusercontent.com/85414302/196058023-4221b6ac-5a9e-459c-a4e2-ece27d87b7cc.png)

### Acceptance Criteria

- [x] Preview release todo issue template updated
- [x] Production release todo issue template updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
