### ISSUE TITLE
🚧Update QA Testing issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#13]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the entire _**Version Being Tested**_ section. 

The reason for this is that releases are more visible and known due to the use of milestones.  Milestones are used as a container for everything that belongs to a particular release.

This makes this section redundant and not required anymore.

**Section To Remove:**
![image](https://user-images.githubusercontent.com/85414302/196207969-434ed5b3-ee4c-4ae4-8767-a04a7b84737e.png)

### Acceptance Criteria

- [ ] _**Version Being Tested**_ removed from template

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
