### ISSUE TITLE
🚧Update QA testing template

### ISSUE THREAD

**Issue by KinsonDigitalAdmin** [KinsonDigital/.github#15]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the QA testing template by changing the description of the first checkbox at the top of the template.
Change the description of the checkbox to `I have reviewed and tested all of the issues in the linked milestone.`

**Checkbox that needs changing:**
![image](https://user-images.githubusercontent.com/105235056/196296280-d1b17946-2f97-4395-9a3b-2dfeb1166cef.png)

### Acceptance Criteria

- [x] QA issue template updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
