### ISSUE TITLE
🚧Update release todo issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#45]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update both the preview and production release todo issue templates by adding 2 new checkboxes to the ToDo list.
These checkboxes will deal with performing documentation website changes for both tutorials and/or API changes and only if it is applicable.

These 2 checkboxes will go right below the existing checkboxes below the _**Post-Release ToDo List**_ section.

**This is what it should look like:**
![image](https://user-images.githubusercontent.com/85414302/230723611-30b0d448-4c18-4aa0-8eff-ea3b83583e26.png)

**The files to change:**
1. **_preview-release-todo-issue-template.yml_**
```diff
- type: checkboxes
  attributes:
    label: Post-Release ToDo List
    description: Verify that release went smoothly.
    options:
    - label: The GitHub release has been created and is correct. 
    - label: The NuGet package has been successfully deployed to [nuget.org](https://www.nuget.org/) _(if applicable)_.
    - label: Announcement of release on [Twitter](https://twitter.com/KDCoder) verified _(if applicable)_. _(Announcement should be performed automatically with the release)_.
    - label: Announcement has been pushed to the [Discord](https://discord.gg/qewu6fNgv7) channel _(if applicable)_.
+  - label: Documentation website released with updated or added tutorials. _(if applicable)_
+  - label: Documentation website released with updated API changes. _(if applicable)_
```
3. _**production-release-todo-issue-template.yml**_
```diff
- type: checkboxes
  attributes:
    label: Post-Release ToDo List
    description: Verify that release went smoothly.
    options:
    - label: The GitHub release has been created and is correct. 
    - label: The NuGet package has been successfully deployed to [nuget.org](https://www.nuget.org/) _(if applicable)_.
    - label: Announcement of release on [Twitter](https://twitter.com/KDCoder) verified _(if applicable)_. _(Announcement should be performed automatically with the release)_.
    - label: Announcement has been pushed to the [Discord](https://discord.gg/qewu6fNgv7) channel _(if applicable)_.
+  - label: Documentation website released with updated or added tutorials. _(if applicable)_
+  - label: Documentation website released with updated API changes. _(if applicable)_
```

### Acceptance Criteria

- [ ] Preview release todo issue template updated
- [ ] Production release todo issue template updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
