### ISSUE TITLE
🚧Remove cicd folder with contents

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#52]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the _**cicd/**_ folder and all of its contents.  This folder contains the typescript scripts for validating tags and releases notes.

After further thought, this is indeed infrastructure stuff and should be in the infrastructure repository.  This is the same location where the reusable workflows exist.

I have already moved the scripts to the [Infrastructure](https://github.com/KinsonDigital/Infrastructure/tree/master/cicd) repo.  All that is needed is to clean them up from this repository.

### Acceptance Criteria

- [x] _**cicd/**_ folder and all contents deleted

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
