### ISSUE TITLE
🚧Add .editorconfig files to the org repo

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#54]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the following **_.editorconfig_** files to this repo.
The files should be added to the _**./config**_ directory.

The name of the files should both be _**solution-level.editorconfig**_ and _**test-level.editorconfig**_. The location of both of 

The files to add are shown below:
> **Note** Click them to download the file.  It is a markdown file but that does not matter.  Copy the content into a new file with the requested names mentioned above.
- [solution-level.editorconfig](https://github.com/KinsonDigital/.github/files/11634921/solution-level.editorconfig.md)
- [test-level..editorconfig](https://github.com/KinsonDigital/.github/files/11634853/test-level.editorconfig.md)

### Acceptance Criteria

- [x] The _**solution-level.editorconfig**_  file added to the _**./config**_ directory
- [x] The _**test-level.editorconfig**_ file added to the _**./config**_ directory

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
