### ISSUE TITLE
🚧Create new branching diagrams

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#56]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create new branching diagrams for new simpler branching model for NON-GitHub action projects.

This branching model diagram file name should be _**trunk-branching-dark-mode-v1.0**_ and _**trunk-branching-light-mode-v1.0**_.

After this issue is complete, create issues for each project that uses the new branching model, to point to the new diagram.

### Acceptance Criteria

- [ ] new branching diagram created
- [ ] Create a tag for the current version
- [ ] issues created for each project that will use the diagram, to migrate to the new diagram
- [ ] Create a new tag for the new version of this documents.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
