### ISSUE TITLE
🚧Update all contribution docs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#59]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update all contribution documentation including branching diagrams to explain the new branching model and dev practices.

**What to do:**
1. Currently, there are docs on branching models 1 and 2.  These need to be deleted and combined into a single document.
2. Update the CONTRIBUTING.md document
3. Create a new version of the _**CreatingModel1Branches.md**_ file which explains how to create a new branch using git commands.
    > **Note** This referenced in the _**CONTRIBUTING.md**_ file
4. Update the _**HowToFork.md**_ if needed by improving the doc
5. Delete the _**Preview-Release-Notes-Sample.md**_ file
6. Delete the _**Production-Release-Notes-Sample.md**_ file
7. Delete the _**ProjectBranchingModelList.md**_ file.
    > **Note** This file is no longer needed because all projects now use the same branching model.
    - This is referenced in the _**CONTRIBUTING.md**_ file.  Update the file to not ref anymore.
8. All changed documents are checked for grammar and spelling mistakes.

### Acceptance Criteria

- [x] The _**BranchingModel1.md**_ and _**BranchingModel2.md**_ docs are combined and updated.
- [x] The _**CONTRIBUTING.md**_ doc updated
- [x] The _**CreatingModel1Branches.md**_ file updated for creating branches for the new branching model
    - [x] Renamed to _**CreatingModelBranches.md**_
    - [x] Reference to this document updated
- [x] The _**CreatingModel2Branches.md**_ file deleted.
- [x] The _**HowToFork.md**_ doc improved and updated.
- [x] The _**Preview-Release-Notes-Sample.md**_ file deleted.
- [x] The _**Production-Release-Notes-Sample.md**_ file deleted.
- [x] The _**ProjectBranchingModelList.md**_ file updated.
    > **Note** This file is no longer needed because all projects now use the same branching model.
    - [x] This is referenced in the _**CONTRIBUTING.md**_ file.  Update the file to not ref anymore.
- [x] All changed documents are checked for grammar and spelling mistakes.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
