### ISSUE TITLE
🚧Update issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#61]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the issue templates to better reflect all of the branching model changes.

This means removing the check-boxes described below:

### Update _**project-item-issue-template.yml**_ Issue Template
**Update 1:**
```diff
- type: checkboxes
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review.
    options:
    - label: Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
    - label: Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
-    - label: Issue linked to the correct project _(if applicable)_.
    - label: Issue linked to the correct milestone _(if applicable)_.
-    - label: Draft pull request created and linked to this issue _(only required with code changes)_.
```
**Update 2:**
```diff
      | Change Type         | Label                |
      |---------------------|----------------------|
      | Bug Fixes           | `🐛bug` |
      | Breaking Changes    | `🧨breaking changes` |
      | New Feature         | `✨new feature` |
      | CICD Changes        | `♻️cicd` |
+     | Config Changes      | `⚙️config` |
+     | Performance Improvements | `🏎️performance` |
      | Code Doc Changes    | `🗒️documentation/code` |
      | Product Doc Changes | `📝documentation/product` |
```

### Update _**research-issue-template**_ Issue Template
```diff
- type: checkboxes
  attributes:
    label: ToDo Items
    options:
    - label: Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
-    - label: Issue linked to the correct project.
```

**Reason:**
With the new syncing system, there is no point in checking these 2 items since they are all automated now.

### Acceptance Criteria

- [x] Project Item Issue Template Updated
  - [x] Checkbox for correct project removed
  - [x] Checkbox for draft pull request linked removed
- [x] Research Issue Template Updated
  - [x] Checkbox for correct project removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
