### ISSUE TITLE
🚧Update contribution guide

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#64]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the following section right above the **DO's and DON'Ts** section

> **Note** This was taken from the [fluent assertions](https://github.com/fluentassertions/fluentassertions/blob/develop/CONTRIBUTING.md) contribution doc

New Section Below:
---
    Finding Existing Issues
    Before filing a new issue, please search the project's issues to check if it already exists.
    
    If you do find an existing issue, please include your own feedback in the discussion. Instead of posting "me too", upvote the issue with 👍, as this better helps us prioritize popular issues and avoids spamming people subscribing to the issue.
    
    Writing a Good Bug Report
    Good bug reports make it easier for maintainers to verify and root cause the underlying problem. The better a bug report, the faster the problem will be resolved. Ideally, a bug report should contain the following information:
    
    A high-level description of the problem.
    A minimal reproduction, i.e. the smallest size of code/configuration required to reproduce the wrong behavior.
    A description of the expected behavior, contrasted with the actual behavior observed.
    Information on the environment: nuget version, .NET version, etc.
    Additional information, e.g. is it a regression from previous versions? are there any known workarounds?
    When ready to submit a bug report, please use the projects **🐛Bug** issue template.
    
    Why are Minimal Reproductions Important?
    A reproduction lets maintainers verify the presence of a bug, and diagnose the issue using a debugger. A minimal reproduction is the smallest possible console application demonstrating that bug. Minimal reproductions are generally preferable since they:
    
    Focus debugging efforts on a simple code snippet,
    Ensure that the problem is not caused by unrelated dependencies/configuration,
    Avoid the need to share production codebases.
    How to Create a Minimal Reproduction
    The best way to create a minimal reproduction is gradually removing code and dependencies from a reproducing app, until the problem no longer occurs. A good minimal reproduction:
    
    Excludes all unnecessary types, methods, code blocks, source files, nuget dependencies and project configurations.
    Contains documentation or code comments illustrating expected vs actual behavior.
    Stack Overflow has a great article about [how to create a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### Acceptance Criteria

- [x] Section added

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
