### ISSUE TITLE
🚧Update bug issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#66]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the _**bug-issue-template.yml**_ file by replacing the operating systems checkboxes with a dropdown.

This is a new feature that GitHub has released.  This lets you have a drop-down in the issue form to choose multiples items from a list.

**Refactor the OS checkbox to:**
```diff
- - type: checkboxes
+ - type: dropdown
  attributes:
    label: Operating System(s)
    description: Which operating system(s) does the bug occur?
+ multiple: true
    options:
-    - label: Windows
+    - Windows
-    - label: Linux
+    - Linux
-    - label: Android
+    - Android
-    - label: Mac OS
+    - Mac OS
-    - label: iOS
+    - iOS
-    - label: Other
+    - Other
  validations:
    required: true
```

**This is what is used to be:**
```yml
- type: checkboxes
  attributes:
    label: Operating System(s)
    description: Which operating system(s) does the bug occur?
    options:
    - label: Windows
    - label: Linux
    - label: Android
    - label: Mac OS
    - label: iOS
    - label: Other
  validations:
    required: true
```

**This is what it should be:**
```yml
- type: dropdown
  id: operating-systems
  attributes:
    label: Operating System(s)
    description: Which operating system(s) does the bug occur?
    multiple: true
    options:
    - Windows
    - Linux
    - Android
    - Mac OS
    - iOS
    - Other
  validations:
    required: true
```

### Acceptance Criteria

- [ ] checkboxes for choosing the OS changed to a dropdown

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
