### ISSUE TITLE
🚧Add run tests info to issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#79]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a ToDo item with an _**> [!Important]**_ admonition and info about running unit tests before submitting PRs.

**Reason:**
We are running into issues where unit tests are passing remotely in the status checks but not locally.  There are all kinds of reasons that this can occur but encouraging the execution of unit tests manually and locally can help reduce these issues.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Info added to project item issue template
- [x] Info added to bug issue template
- [x] Acceptance criteria added to bug issue template
```

### ToDo Items

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
